env:
  browser: true
  es2021: true
  jest: true
settings: {
  react: {
    version: 'detect',
  }
}
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'react/react-in-jsx-scope': 'off',
  'prettier/prettier': [
    'warn',
    {
      singleQuote: true,
      semi: false,
      indentStyle: 'space',
      indentSize: 2,
      trimTrailingWhitespace: true,
      insertFinalNewline: true,
      printWidth: 120,
      trailingComma: all,
    },
  ],
}
globals:
  JSX: true
