export const REST_ROUTES = {
  allReleases: '/rest/v1/releases/all',
  authenticated: '/rest/v1/auth',
  cover: '/rest/v1/releases/cover-reload',
  csrf: '/rest/v1/csrf',
  currentUser: '/rest/v1/me',
  followArtist: '/rest/v1/artists/follow',
  forgotPassword: '/rest/v1/auth/forgot-password',
  imports: '/rest/v1/releases/import',
  mostExpectedReleases: '/rest/v1/releases/top',
  mostFollowedArtists: '/rest/v1/artists/top',
  myArtists: '/rest/v1/my-artists',
  refresh: '/rest/v1/auth/refresh',
  releases: '/rest/v1/releases',
  resetPassword: '/rest/v1/auth/reset-password',
  searchArtists: '/rest/v1/artists/search',
  signIn: '/rest/v1/auth/login',
  signOut: '/rest/v1/auth/logout',
  signUp: '/rest/v1/auth/register',
  signUpVerification: '/rest/v1/auth/register/verification',
  unfollowArtist: '/rest/v1/artists/unfollow',
  updateEmailAddress: '/rest/v1/me/email',
  updatePassword: '/rest/v1/me/password',
  users: '/rest/v1/users',
}
