name: Continuous integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm test -- --coverage
