name: Continuous integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # 4.2.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # 4.0.4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm install
#          npm test -- --coverage TODO: enable after migration to vite is done
