name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Create version string
        id: version
        run: echo "version=$(date -u +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # 3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push to DockerHub
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # 6.15.0
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            metaldetectorrocks/metal-detector-frontend:${{ env.version }}
            metaldetectorrocks/metal-detector-frontend:latest
          build-args: |
            BUILD_DATE=${{ env.version }}
            VCS_REF=${{ github.ref }}
