name: Build docker image

on:
  push:
    branches:
      - main
#  TODO: remove, only for test
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: Create version string
        id: version
        run: echo "::set-output name=version::$(date -u +'%Y%m%dT%H%M%S')"

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            metaldetector/metal-detector-frontend:${{ steps.version.outputs.version }}
            metaldetector/metal-detector-frontend:latest
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.version }}
            VCS_REF=${{ github.ref }}
