name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Create version string
        id: version
        run: echo "::set-output name=version::$(date -u +'%Y%m%dT%H%M%S')"

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # 3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push to DockerHub
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # 6.12.0
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            metaldetectorrocks/metal-detector-frontend:${{ steps.version.outputs.version }}
            metaldetectorrocks/metal-detector-frontend:latest
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.version }}
            VCS_REF=${{ github.ref }}
