name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4

      - name: Create version string
        id: version
        run: echo "::set-output name=version::$(date -u +'%Y%m%dT%H%M%S')"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            metaldetectorrocks/metal-detector-frontend:${{ steps.version.outputs.version }}
            metaldetectorrocks/metal-detector-frontend:latest
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.version }}
            VCS_REF=${{ github.ref }}
