name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout git repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1

      - name: Create version string
        id: version
        run: echo "::set-output name=version::$(date -u +'%Y%m%dT%H%M%S')"

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # 3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push to DockerHub
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # 6.9.0
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            metaldetectorrocks/metal-detector-frontend:${{ steps.version.outputs.version }}
            metaldetectorrocks/metal-detector-frontend:latest
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.version }}
            VCS_REF=${{ github.ref }}
