name: Lint

on: push

jobs:
  run-linters:
    name: Run linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout git repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1

      - name: setup node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # 4.0.4
        with:
          node-version: 22

      - name: install dependencies
        run: npm install

      - name: run eslint
        run: npm run lint
